# application-docker.yml (Docker 컨테이너용)
spring:
  #  인메모리 데이터베이스 사용 (별도 DB 설치 불필요) TODO Mysql로 변경
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/springdb
    username: springuser
    password: p@ss

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

# JWT 설정
app:
  jwt:
    secret: dockerJwtSecretKey123456789012345678901234567890
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

# 로깅
logging:
  level:
    com.example.webapp: INFO
    org.hibernate.SQL: DEBUG