# application-prod.yml (운영환경)
spring:
  # 운영용 MySQL 설정
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/springdb_prod}
    username: ${DATABASE_USERNAME:springuser}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000

  jpa:
    hibernate:
      ddl-auto: validate  # 운영에서는 스키마 변경 금지
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# 운영 환경 JWT 설정 (모두 환경변수 사용)
app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

# 운영용 로깅
logging:
  level:
    com.example: INFO
    com.example.webapp: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN