# application-dev.yml (개발환경)
spring:
  # MySQL 데이터베이스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb?allowPublicKeyRetrieval=true&useSSL=false
    username: springuser
    password: p@ss

  # SQL 초기화 설정
  sql:
    init:
      mode: always

  # JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true
    open-in-view: false

# JWT 개발환경 설정
app:
  jwt:
    secret: myJwtSecretKey123456789012345678901234567890
    access-token-expiration: 900000  # 15분
    refresh-token-expiration: 604800000  # 7일

# 로깅 설정
logging:
  level:
    com.example: DEBUG
    com.example.webapp: TRACE
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"