# application.yml (기본 설정)
server:
  port: 8080

spring:
  application:
    name: webapp

  profiles:
    active: dev

  # Jackson 설정 (JSON 처리)
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

# JWT 기본 설정
app:
  jwt:
    # 토큰 접두사
    token-prefix: "Bearer "
    # Authorization 헤더명
    header-name: "Authorization"
    # JWT 발급자
    issuer: "jwt-demo-api"
    # JWT 대상
    audience: "jwt-demo-users"

# 관리자 도구 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized